"""
WebSocket routes for real-time pipeline progress updates.
"""

import logging

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from src.websocket.manager import ws_manager

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ws", tags=["websocket"])


@router.websocket("/constraints/{session_id}")
async def websocket_constraint_progress(websocket: WebSocket, session_id: str):
    """
    WebSocket endpoint for receiving real-time LLM pipeline progress updates.
    
    The client connects with a session_id before initiating the constraint preview request.
    The same session_id is passed to the preview endpoint to link the WebSocket with the request.
    
    Message format (server -> client):
    {
        "type": "stage_update",
        "stage": "translating" | "understanding" | "processing" | "validating" | "extracting" | "finalizing" | "complete" | "error",
        "display_text": "Human-readable stage description",
        "progress": 0-100,
        "status": "in_progress" | "complete" | "error"
    }
    
    Args:
        websocket: The WebSocket connection
        session_id: Unique session identifier (UUID) generated by the client
    """
    await ws_manager.connect(session_id, websocket)
    
    try:
        # Keep connection alive and handle incoming messages (if any)
        while True:
            # We don't expect messages from the client, but need to keep receiving
            # to detect disconnection. Using a timeout to periodically check.
            try:
                # Wait for any message (ping/pong handled automatically by FastAPI)
                data = await websocket.receive_text()
                
                # Client can send "ping" to keep alive
                if data == "ping":
                    await websocket.send_text("pong")
                    
            except WebSocketDisconnect:
                break
                
    except Exception as e:
        logger.error(f"WebSocket error for session {session_id}: {e}")
        
    finally:
        await ws_manager.disconnect(session_id, websocket)
